### ISSUE TITLE
scrollbar in mobile

### ISSUE THREAD

**Issue by Rootom360** [WebCifar/one-page-website-html-css-project-for-practice#1]
Hello arhan, first of all Thank you for teaching us how to make this insane website,  And appriciate your work.

Actually i write every single line of code by watching your youtube video but at the end it's not looking at same as your website, so i came to your github page and copied all style.css code, all thing is working properly but i am getting scrollbar issue in my mobile.

MAIN ISSUE : Scrollbar showing in mobile.

**Comment by ShaifArfan** [comment]
can i see the code?. [you can send me githu  repo]
